// Proto definitions for the launchpad-service.
// Build with: protoc --go_out=. --go-grpc_out=. proto/launchpad.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: launchpad.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Launchpad_Healthz_FullMethodName      = "/rial.launchpad.v1.Launchpad/Healthz"
	Launchpad_CreateToken_FullMethodName  = "/rial.launchpad.v1.Launchpad/CreateToken"
	Launchpad_GetToken_FullMethodName     = "/rial.launchpad.v1.Launchpad/GetToken"
	Launchpad_ListTokens_FullMethodName   = "/rial.launchpad.v1.Launchpad/ListTokens"
	Launchpad_ApproveToken_FullMethodName = "/rial.launchpad.v1.Launchpad/ApproveToken"
	Launchpad_RejectToken_FullMethodName  = "/rial.launchpad.v1.Launchpad/RejectToken"
	Launchpad_PauseToken_FullMethodName   = "/rial.launchpad.v1.Launchpad/PauseToken"
	Launchpad_QuoteBuy_FullMethodName     = "/rial.launchpad.v1.Launchpad/QuoteBuy"
	Launchpad_Buy_FullMethodName          = "/rial.launchpad.v1.Launchpad/Buy"
	Launchpad_Sell_FullMethodName         = "/rial.launchpad.v1.Launchpad/Sell"
	Launchpad_GetVesting_FullMethodName   = "/rial.launchpad.v1.Launchpad/GetVesting"
)

// LaunchpadClient is the client API for Launchpad service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LaunchpadClient interface {
	Healthz(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	ListTokens(ctx context.Context, in *ListTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error)
	ApproveToken(ctx context.Context, in *TokenActionRequest, opts ...grpc.CallOption) (*Empty, error)
	RejectToken(ctx context.Context, in *RejectTokenRequest, opts ...grpc.CallOption) (*Empty, error)
	PauseToken(ctx context.Context, in *PauseTokenRequest, opts ...grpc.CallOption) (*Empty, error)
	QuoteBuy(ctx context.Context, in *QuoteBuyRequest, opts ...grpc.CallOption) (*BuyQuoteResponse, error)
	Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyResultResponse, error)
	Sell(ctx context.Context, in *SellRequest, opts ...grpc.CallOption) (*BuyResultResponse, error)
	GetVesting(ctx context.Context, in *GetVestingRequest, opts ...grpc.CallOption) (*VestingResponse, error)
}

type launchpadClient struct {
	cc grpc.ClientConnInterface
}

func NewLaunchpadClient(cc grpc.ClientConnInterface) LaunchpadClient {
	return &launchpadClient{cc}
}

func (c *launchpadClient) Healthz(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Launchpad_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, Launchpad_CreateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, Launchpad_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) ListTokens(ctx context.Context, in *ListTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTokensResponse)
	err := c.cc.Invoke(ctx, Launchpad_ListTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) ApproveToken(ctx context.Context, in *TokenActionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Launchpad_ApproveToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) RejectToken(ctx context.Context, in *RejectTokenRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Launchpad_RejectToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) PauseToken(ctx context.Context, in *PauseTokenRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Launchpad_PauseToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) QuoteBuy(ctx context.Context, in *QuoteBuyRequest, opts ...grpc.CallOption) (*BuyQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyQuoteResponse)
	err := c.cc.Invoke(ctx, Launchpad_QuoteBuy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyResultResponse)
	err := c.cc.Invoke(ctx, Launchpad_Buy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) Sell(ctx context.Context, in *SellRequest, opts ...grpc.CallOption) (*BuyResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyResultResponse)
	err := c.cc.Invoke(ctx, Launchpad_Sell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *launchpadClient) GetVesting(ctx context.Context, in *GetVestingRequest, opts ...grpc.CallOption) (*VestingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VestingResponse)
	err := c.cc.Invoke(ctx, Launchpad_GetVesting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LaunchpadServer is the server API for Launchpad service.
// All implementations must embed UnimplementedLaunchpadServer
// for forward compatibility.
type LaunchpadServer interface {
	Healthz(context.Context, *Empty) (*HealthResponse, error)
	CreateToken(context.Context, *CreateTokenRequest) (*TokenResponse, error)
	GetToken(context.Context, *GetTokenRequest) (*TokenResponse, error)
	ListTokens(context.Context, *ListTokensRequest) (*ListTokensResponse, error)
	ApproveToken(context.Context, *TokenActionRequest) (*Empty, error)
	RejectToken(context.Context, *RejectTokenRequest) (*Empty, error)
	PauseToken(context.Context, *PauseTokenRequest) (*Empty, error)
	QuoteBuy(context.Context, *QuoteBuyRequest) (*BuyQuoteResponse, error)
	Buy(context.Context, *BuyRequest) (*BuyResultResponse, error)
	Sell(context.Context, *SellRequest) (*BuyResultResponse, error)
	GetVesting(context.Context, *GetVestingRequest) (*VestingResponse, error)
	mustEmbedUnimplementedLaunchpadServer()
}

// UnimplementedLaunchpadServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLaunchpadServer struct{}

func (UnimplementedLaunchpadServer) Healthz(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedLaunchpadServer) CreateToken(context.Context, *CreateTokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToken not implemented")
}
func (UnimplementedLaunchpadServer) GetToken(context.Context, *GetTokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedLaunchpadServer) ListTokens(context.Context, *ListTokensRequest) (*ListTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTokens not implemented")
}
func (UnimplementedLaunchpadServer) ApproveToken(context.Context, *TokenActionRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveToken not implemented")
}
func (UnimplementedLaunchpadServer) RejectToken(context.Context, *RejectTokenRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectToken not implemented")
}
func (UnimplementedLaunchpadServer) PauseToken(context.Context, *PauseTokenRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseToken not implemented")
}
func (UnimplementedLaunchpadServer) QuoteBuy(context.Context, *QuoteBuyRequest) (*BuyQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteBuy not implemented")
}
func (UnimplementedLaunchpadServer) Buy(context.Context, *BuyRequest) (*BuyResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buy not implemented")
}
func (UnimplementedLaunchpadServer) Sell(context.Context, *SellRequest) (*BuyResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sell not implemented")
}
func (UnimplementedLaunchpadServer) GetVesting(context.Context, *GetVestingRequest) (*VestingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVesting not implemented")
}
func (UnimplementedLaunchpadServer) mustEmbedUnimplementedLaunchpadServer() {}
func (UnimplementedLaunchpadServer) testEmbeddedByValue()                   {}

// UnsafeLaunchpadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LaunchpadServer will
// result in compilation errors.
type UnsafeLaunchpadServer interface {
	mustEmbedUnimplementedLaunchpadServer()
}

func RegisterLaunchpadServer(s grpc.ServiceRegistrar, srv LaunchpadServer) {
	// If the following call pancis, it indicates UnimplementedLaunchpadServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Launchpad_ServiceDesc, srv)
}

func _Launchpad_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).Healthz(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_CreateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).CreateToken(ctx, req.(*CreateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_ListTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).ListTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_ListTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).ListTokens(ctx, req.(*ListTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_ApproveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).ApproveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_ApproveToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).ApproveToken(ctx, req.(*TokenActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_RejectToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).RejectToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_RejectToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).RejectToken(ctx, req.(*RejectTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_PauseToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).PauseToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_PauseToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).PauseToken(ctx, req.(*PauseTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_QuoteBuy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteBuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).QuoteBuy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_QuoteBuy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).QuoteBuy(ctx, req.(*QuoteBuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_Buy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).Buy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_Buy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).Buy(ctx, req.(*BuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_Sell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).Sell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_Sell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).Sell(ctx, req.(*SellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Launchpad_GetVesting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVestingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaunchpadServer).GetVesting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Launchpad_GetVesting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaunchpadServer).GetVesting(ctx, req.(*GetVestingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Launchpad_ServiceDesc is the grpc.ServiceDesc for Launchpad service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Launchpad_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rial.launchpad.v1.Launchpad",
	HandlerType: (*LaunchpadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _Launchpad_Healthz_Handler,
		},
		{
			MethodName: "CreateToken",
			Handler:    _Launchpad_CreateToken_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _Launchpad_GetToken_Handler,
		},
		{
			MethodName: "ListTokens",
			Handler:    _Launchpad_ListTokens_Handler,
		},
		{
			MethodName: "ApproveToken",
			Handler:    _Launchpad_ApproveToken_Handler,
		},
		{
			MethodName: "RejectToken",
			Handler:    _Launchpad_RejectToken_Handler,
		},
		{
			MethodName: "PauseToken",
			Handler:    _Launchpad_PauseToken_Handler,
		},
		{
			MethodName: "QuoteBuy",
			Handler:    _Launchpad_QuoteBuy_Handler,
		},
		{
			MethodName: "Buy",
			Handler:    _Launchpad_Buy_Handler,
		},
		{
			MethodName: "Sell",
			Handler:    _Launchpad_Sell_Handler,
		},
		{
			MethodName: "GetVesting",
			Handler:    _Launchpad_GetVesting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "launchpad.proto",
}
